### ISSUE TITLE
To-do issue list

### ISSUE THREAD

**Issue by GurrenLagannTSS** [GurrenLagannTSS/VASPSTools#1]
For depulsator.py:
- [ ] Verify if it works on other similar variable types
- [ ] Support Systemic vels files (text-based, `JulianDate RadialVelocity Err`)
- [ ] Support light curves from LCTools
- [ ] Support light curves from OGLE database
- [ ] Add the ability to bin data
- [ ] Add ability to derive times of minima and/or maxima
- [ ] Figure out a way to automate this at a massive scale
